import { useEffect, useRef, useState } from "react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogFooter } from "@/components/ui/dialog";
import { Check, Loader2, Lock, Wand2 } from "lucide-react";
import { cn } from "@/lib/utils";
import { CT_UNLOCK_PASSWORD, CT_MIN_WEEK_GAP } from "@/lib/constants";
import { toast } from "sonner";

const STEPS = [
  { title: "Reading configuration", detail: "Available weeks, days and room mappings" },
  { title: "Placing class tests", detail: `CT 1 → 2 → 3, ${CT_MIN_WEEK_GAP} weeks apart per course` },
  { title: "Saving schedule", detail: "Writing assignments to the semester" },
];

interface CTGenerateButtonProps {
  /** True once a schedule exists — the button locks until the password is entered. */
  hasSchedule: boolean;
  /** Runs the actual generation. Rejections are surfaced by the caller's toast. */
  onGenerate: () => Promise<void>;
  label?: string;
  className?: string;
}

/** Generate button for the CT schedule, with a three-step progress dialog and a
 *  password lock that prevents an existing schedule being regenerated by accident. */
export function CTGenerateButton({
  hasSchedule,
  onGenerate,
  label = "Generate CT Schedule",
  className,
}: CTGenerateButtonProps) {
  const [unlocked, setUnlocked] = useState(false);
  const [showUnlock, setShowUnlock] = useState(false);
  const [password, setPassword] = useState("");
  const [passwordError, setPasswordError] = useState(false);

  const [generating, setGenerating] = useState(false);
  const [step, setStep] = useState(0);
  const timers = useRef<number[]>([]);

  // Re-lock whenever a schedule comes into existence (including right after a run).
  useEffect(() => {
    if (hasSchedule) setUnlocked(false);
  }, [hasSchedule]);

  useEffect(() => () => timers.current.forEach((t) => window.clearTimeout(t)), []);

  const locked = hasSchedule && !unlocked;

  const runGeneration = async () => {
    setGenerating(true);
    setStep(0);
    // The server does not stream progress, so the first two steps advance on a timer
    // and the last one resolves with the request itself.
    timers.current = [
      window.setTimeout(() => setStep(1), 700),
      window.setTimeout(() => setStep(2), 1600),
    ];
    try {
      await onGenerate();
      timers.current.forEach((t) => window.clearTimeout(t));
      setStep(STEPS.length);
      await new Promise((r) => window.setTimeout(r, 600));
    } finally {
      timers.current.forEach((t) => window.clearTimeout(t));
      setGenerating(false);
      setStep(0);
    }
  };

  const submitPassword = () => {
    if (password === CT_UNLOCK_PASSWORD) {
      setUnlocked(true);
      setShowUnlock(false);
      setPassword("");
      setPasswordError(false);
      toast.success("Unlocked — you can regenerate the CT schedule");
    } else {
      setPasswordError(true);
    }
  };

  return (
    <>
      {locked ? (
        <Button
          variant="outline"
          onClick={() => {
            setPassword("");
            setPasswordError(false);
            setShowUnlock(true);
          }}
          className={cn("font-bold border-2 border-amber-500/50 text-amber-600 hover:bg-amber-500/10", className)}
          title="A CT schedule already exists — unlock to regenerate"
        >
          <Lock className="mr-2 h-4 w-4" />
          Locked
        </Button>
      ) : (
        <Button
          onClick={runGeneration}
          disabled={generating}
          className={cn("bg-gradient-to-r from-primary to-primary/80 font-bold", className)}
        >
          {generating ? <Loader2 className="mr-2 h-4 w-4 animate-spin" /> : <Wand2 className="mr-2 h-4 w-4" />}
          {label}
        </Button>
      )}

      {/* Unlock */}
      <Dialog open={showUnlock} onOpenChange={(open) => !open && setShowUnlock(false)}>
        <DialogContent className="sm:max-w-[420px]">
          <DialogHeader>
            <DialogTitle className="flex items-center gap-2">
              <Lock className="h-4 w-4 text-amber-600" /> Unlock CT generation
            </DialogTitle>
          </DialogHeader>
          <div className="space-y-3 py-2">
            <p className="text-sm text-muted-foreground">
              A CT schedule already exists. Regenerating replaces every existing assignment,
              including any dates or rooms edited by hand. Enter the password to continue.
            </p>
            <div className="grid gap-2">
              <Label htmlFor="ct-unlock-password">Password</Label>
              <Input
                id="ct-unlock-password"
                type="password"
                autoFocus
                value={password}
                onChange={(e) => {
                  setPassword(e.target.value);
                  setPasswordError(false);
                }}
                onKeyDown={(e) => e.key === "Enter" && submitPassword()}
                className={cn(passwordError && "border-destructive focus-visible:ring-destructive")}
                placeholder="Enter unlock password"
              />
              {passwordError && (
                <span className="text-xs font-semibold text-destructive">Incorrect password.</span>
              )}
            </div>
          </div>
          <DialogFooter>
            <Button variant="outline" onClick={() => setShowUnlock(false)}>
              Cancel
            </Button>
            <Button onClick={submitPassword} disabled={password.length === 0}>
              Unlock
            </Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>

      {/* Three-step progress */}
      <Dialog open={generating}>
        <DialogContent
          className="sm:max-w-[440px] [&>button]:hidden"
          onEscapeKeyDown={(e) => e.preventDefault()}
          onInteractOutside={(e) => e.preventDefault()}
        >
          <DialogHeader>
            <DialogTitle>Generating CT schedule</DialogTitle>
          </DialogHeader>
          <div className="space-y-1 py-2">
            {STEPS.map((s, i) => {
              const done = step > i;
              const active = step === i;
              return (
                <div
                  key={s.title}
                  className={cn(
                    "flex items-start gap-3 rounded-xl p-3 transition-all",
                    active && "bg-primary/10",
                    !active && !done && "opacity-50"
                  )}
                >
                  <div
                    className={cn(
                      "mt-0.5 flex h-7 w-7 shrink-0 items-center justify-center rounded-full text-xs font-black transition-all",
                      done && "bg-success/20 text-success",
                      active && "bg-primary/20 text-primary",
                      !done && !active && "bg-muted text-muted-foreground"
                    )}
                  >
                    {done ? (
                      <Check className="h-4 w-4" />
                    ) : active ? (
                      <Loader2 className="h-4 w-4 animate-spin" />
                    ) : (
                      i + 1
                    )}
                  </div>
                  <div className="min-w-0">
                    <div className="text-sm font-bold">{s.title}</div>
                    <div className="text-xs text-muted-foreground">{s.detail}</div>
                  </div>
                </div>
              );
            })}
          </div>
          <div className="h-1.5 w-full overflow-hidden rounded-full bg-muted">
            <div
              className="h-full rounded-full bg-gradient-to-r from-primary to-primary/70 transition-all duration-500"
              style={{ width: `${(step / STEPS.length) * 100}%` }}
            />
          </div>
        </DialogContent>
      </Dialog>
    </>
  );
}
