/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TeachersRouteImport } from './routes/teachers'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SemesterSettingsRouteImport } from './routes/semester-settings'
import { Route as SectionsRouteImport } from './routes/sections'
import { Route as RoutineRouteImport } from './routes/routine'
import { Route as RoomsRouteImport } from './routes/rooms'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as PriorityClassesRouteImport } from './routes/priority-classes'
import { Route as MappingRouteImport } from './routes/mapping'
import { Route as LockedClassesRouteImport } from './routes/locked-classes'
import { Route as GenerateRoutineRouteImport } from './routes/generate-routine'
import { Route as DepartmentsRouteImport } from './routes/departments'
import { Route as CoursesRouteImport } from './routes/courses'
import { Route as ConflictedClassesRouteImport } from './routes/conflicted-classes'
import { Route as AvailabilityRouteImport } from './routes/availability'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CtScheduleViewRouteImport } from './routes/ct-schedule.view'
import { Route as CtScheduleTeachersRouteImport } from './routes/ct-schedule.teachers'
import { Route as CtScheduleTableRouteImport } from './routes/ct-schedule.table'
import { Route as CtScheduleRoomsRouteImport } from './routes/ct-schedule.rooms'
import { Route as CtScheduleConfigRouteImport } from './routes/ct-schedule.config'

const TeachersRoute = TeachersRouteImport.update({
  id: '/teachers',
  path: '/teachers',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SemesterSettingsRoute = SemesterSettingsRouteImport.update({
  id: '/semester-settings',
  path: '/semester-settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SectionsRoute = SectionsRouteImport.update({
  id: '/sections',
  path: '/sections',
  getParentRoute: () => rootRouteImport,
} as any)
const RoutineRoute = RoutineRouteImport.update({
  id: '/routine',
  path: '/routine',
  getParentRoute: () => rootRouteImport,
} as any)
const RoomsRoute = RoomsRouteImport.update({
  id: '/rooms',
  path: '/rooms',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const PriorityClassesRoute = PriorityClassesRouteImport.update({
  id: '/priority-classes',
  path: '/priority-classes',
  getParentRoute: () => rootRouteImport,
} as any)
const MappingRoute = MappingRouteImport.update({
  id: '/mapping',
  path: '/mapping',
  getParentRoute: () => rootRouteImport,
} as any)
const LockedClassesRoute = LockedClassesRouteImport.update({
  id: '/locked-classes',
  path: '/locked-classes',
  getParentRoute: () => rootRouteImport,
} as any)
const GenerateRoutineRoute = GenerateRoutineRouteImport.update({
  id: '/generate-routine',
  path: '/generate-routine',
  getParentRoute: () => rootRouteImport,
} as any)
const DepartmentsRoute = DepartmentsRouteImport.update({
  id: '/departments',
  path: '/departments',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesRoute = CoursesRouteImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => rootRouteImport,
} as any)
const ConflictedClassesRoute = ConflictedClassesRouteImport.update({
  id: '/conflicted-classes',
  path: '/conflicted-classes',
  getParentRoute: () => rootRouteImport,
} as any)
const AvailabilityRoute = AvailabilityRouteImport.update({
  id: '/availability',
  path: '/availability',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CtScheduleViewRoute = CtScheduleViewRouteImport.update({
  id: '/ct-schedule/view',
  path: '/ct-schedule/view',
  getParentRoute: () => rootRouteImport,
} as any)
const CtScheduleTeachersRoute = CtScheduleTeachersRouteImport.update({
  id: '/ct-schedule/teachers',
  path: '/ct-schedule/teachers',
  getParentRoute: () => rootRouteImport,
} as any)
const CtScheduleTableRoute = CtScheduleTableRouteImport.update({
  id: '/ct-schedule/table',
  path: '/ct-schedule/table',
  getParentRoute: () => rootRouteImport,
} as any)
const CtScheduleRoomsRoute = CtScheduleRoomsRouteImport.update({
  id: '/ct-schedule/rooms',
  path: '/ct-schedule/rooms',
  getParentRoute: () => rootRouteImport,
} as any)
const CtScheduleConfigRoute = CtScheduleConfigRouteImport.update({
  id: '/ct-schedule/config',
  path: '/ct-schedule/config',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/availability': typeof AvailabilityRoute
  '/conflicted-classes': typeof ConflictedClassesRoute
  '/courses': typeof CoursesRoute
  '/departments': typeof DepartmentsRoute
  '/generate-routine': typeof GenerateRoutineRoute
  '/locked-classes': typeof LockedClassesRoute
  '/mapping': typeof MappingRoute
  '/priority-classes': typeof PriorityClassesRoute
  '/reports': typeof ReportsRoute
  '/rooms': typeof RoomsRoute
  '/routine': typeof RoutineRoute
  '/sections': typeof SectionsRoute
  '/semester-settings': typeof SemesterSettingsRoute
  '/settings': typeof SettingsRoute
  '/teachers': typeof TeachersRoute
  '/ct-schedule/config': typeof CtScheduleConfigRoute
  '/ct-schedule/rooms': typeof CtScheduleRoomsRoute
  '/ct-schedule/table': typeof CtScheduleTableRoute
  '/ct-schedule/teachers': typeof CtScheduleTeachersRoute
  '/ct-schedule/view': typeof CtScheduleViewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/availability': typeof AvailabilityRoute
  '/conflicted-classes': typeof ConflictedClassesRoute
  '/courses': typeof CoursesRoute
  '/departments': typeof DepartmentsRoute
  '/generate-routine': typeof GenerateRoutineRoute
  '/locked-classes': typeof LockedClassesRoute
  '/mapping': typeof MappingRoute
  '/priority-classes': typeof PriorityClassesRoute
  '/reports': typeof ReportsRoute
  '/rooms': typeof RoomsRoute
  '/routine': typeof RoutineRoute
  '/sections': typeof SectionsRoute
  '/semester-settings': typeof SemesterSettingsRoute
  '/settings': typeof SettingsRoute
  '/teachers': typeof TeachersRoute
  '/ct-schedule/config': typeof CtScheduleConfigRoute
  '/ct-schedule/rooms': typeof CtScheduleRoomsRoute
  '/ct-schedule/table': typeof CtScheduleTableRoute
  '/ct-schedule/teachers': typeof CtScheduleTeachersRoute
  '/ct-schedule/view': typeof CtScheduleViewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/availability': typeof AvailabilityRoute
  '/conflicted-classes': typeof ConflictedClassesRoute
  '/courses': typeof CoursesRoute
  '/departments': typeof DepartmentsRoute
  '/generate-routine': typeof GenerateRoutineRoute
  '/locked-classes': typeof LockedClassesRoute
  '/mapping': typeof MappingRoute
  '/priority-classes': typeof PriorityClassesRoute
  '/reports': typeof ReportsRoute
  '/rooms': typeof RoomsRoute
  '/routine': typeof RoutineRoute
  '/sections': typeof SectionsRoute
  '/semester-settings': typeof SemesterSettingsRoute
  '/settings': typeof SettingsRoute
  '/teachers': typeof TeachersRoute
  '/ct-schedule/config': typeof CtScheduleConfigRoute
  '/ct-schedule/rooms': typeof CtScheduleRoomsRoute
  '/ct-schedule/table': typeof CtScheduleTableRoute
  '/ct-schedule/teachers': typeof CtScheduleTeachersRoute
  '/ct-schedule/view': typeof CtScheduleViewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/availability'
    | '/conflicted-classes'
    | '/courses'
    | '/departments'
    | '/generate-routine'
    | '/locked-classes'
    | '/mapping'
    | '/priority-classes'
    | '/reports'
    | '/rooms'
    | '/routine'
    | '/sections'
    | '/semester-settings'
    | '/settings'
    | '/teachers'
    | '/ct-schedule/config'
    | '/ct-schedule/rooms'
    | '/ct-schedule/table'
    | '/ct-schedule/teachers'
    | '/ct-schedule/view'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/availability'
    | '/conflicted-classes'
    | '/courses'
    | '/departments'
    | '/generate-routine'
    | '/locked-classes'
    | '/mapping'
    | '/priority-classes'
    | '/reports'
    | '/rooms'
    | '/routine'
    | '/sections'
    | '/semester-settings'
    | '/settings'
    | '/teachers'
    | '/ct-schedule/config'
    | '/ct-schedule/rooms'
    | '/ct-schedule/table'
    | '/ct-schedule/teachers'
    | '/ct-schedule/view'
  id:
    | '__root__'
    | '/'
    | '/availability'
    | '/conflicted-classes'
    | '/courses'
    | '/departments'
    | '/generate-routine'
    | '/locked-classes'
    | '/mapping'
    | '/priority-classes'
    | '/reports'
    | '/rooms'
    | '/routine'
    | '/sections'
    | '/semester-settings'
    | '/settings'
    | '/teachers'
    | '/ct-schedule/config'
    | '/ct-schedule/rooms'
    | '/ct-schedule/table'
    | '/ct-schedule/teachers'
    | '/ct-schedule/view'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AvailabilityRoute: typeof AvailabilityRoute
  ConflictedClassesRoute: typeof ConflictedClassesRoute
  CoursesRoute: typeof CoursesRoute
  DepartmentsRoute: typeof DepartmentsRoute
  GenerateRoutineRoute: typeof GenerateRoutineRoute
  LockedClassesRoute: typeof LockedClassesRoute
  MappingRoute: typeof MappingRoute
  PriorityClassesRoute: typeof PriorityClassesRoute
  ReportsRoute: typeof ReportsRoute
  RoomsRoute: typeof RoomsRoute
  RoutineRoute: typeof RoutineRoute
  SectionsRoute: typeof SectionsRoute
  SemesterSettingsRoute: typeof SemesterSettingsRoute
  SettingsRoute: typeof SettingsRoute
  TeachersRoute: typeof TeachersRoute
  CtScheduleConfigRoute: typeof CtScheduleConfigRoute
  CtScheduleRoomsRoute: typeof CtScheduleRoomsRoute
  CtScheduleTableRoute: typeof CtScheduleTableRoute
  CtScheduleTeachersRoute: typeof CtScheduleTeachersRoute
  CtScheduleViewRoute: typeof CtScheduleViewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/teachers': {
      id: '/teachers'
      path: '/teachers'
      fullPath: '/teachers'
      preLoaderRoute: typeof TeachersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/semester-settings': {
      id: '/semester-settings'
      path: '/semester-settings'
      fullPath: '/semester-settings'
      preLoaderRoute: typeof SemesterSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sections': {
      id: '/sections'
      path: '/sections'
      fullPath: '/sections'
      preLoaderRoute: typeof SectionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/routine': {
      id: '/routine'
      path: '/routine'
      fullPath: '/routine'
      preLoaderRoute: typeof RoutineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rooms': {
      id: '/rooms'
      path: '/rooms'
      fullPath: '/rooms'
      preLoaderRoute: typeof RoomsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/priority-classes': {
      id: '/priority-classes'
      path: '/priority-classes'
      fullPath: '/priority-classes'
      preLoaderRoute: typeof PriorityClassesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mapping': {
      id: '/mapping'
      path: '/mapping'
      fullPath: '/mapping'
      preLoaderRoute: typeof MappingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/locked-classes': {
      id: '/locked-classes'
      path: '/locked-classes'
      fullPath: '/locked-classes'
      preLoaderRoute: typeof LockedClassesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/generate-routine': {
      id: '/generate-routine'
      path: '/generate-routine'
      fullPath: '/generate-routine'
      preLoaderRoute: typeof GenerateRoutineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/departments': {
      id: '/departments'
      path: '/departments'
      fullPath: '/departments'
      preLoaderRoute: typeof DepartmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses': {
      id: '/courses'
      path: '/courses'
      fullPath: '/courses'
      preLoaderRoute: typeof CoursesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conflicted-classes': {
      id: '/conflicted-classes'
      path: '/conflicted-classes'
      fullPath: '/conflicted-classes'
      preLoaderRoute: typeof ConflictedClassesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/availability': {
      id: '/availability'
      path: '/availability'
      fullPath: '/availability'
      preLoaderRoute: typeof AvailabilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ct-schedule/view': {
      id: '/ct-schedule/view'
      path: '/ct-schedule/view'
      fullPath: '/ct-schedule/view'
      preLoaderRoute: typeof CtScheduleViewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ct-schedule/teachers': {
      id: '/ct-schedule/teachers'
      path: '/ct-schedule/teachers'
      fullPath: '/ct-schedule/teachers'
      preLoaderRoute: typeof CtScheduleTeachersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ct-schedule/table': {
      id: '/ct-schedule/table'
      path: '/ct-schedule/table'
      fullPath: '/ct-schedule/table'
      preLoaderRoute: typeof CtScheduleTableRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ct-schedule/rooms': {
      id: '/ct-schedule/rooms'
      path: '/ct-schedule/rooms'
      fullPath: '/ct-schedule/rooms'
      preLoaderRoute: typeof CtScheduleRoomsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ct-schedule/config': {
      id: '/ct-schedule/config'
      path: '/ct-schedule/config'
      fullPath: '/ct-schedule/config'
      preLoaderRoute: typeof CtScheduleConfigRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AvailabilityRoute: AvailabilityRoute,
  ConflictedClassesRoute: ConflictedClassesRoute,
  CoursesRoute: CoursesRoute,
  DepartmentsRoute: DepartmentsRoute,
  GenerateRoutineRoute: GenerateRoutineRoute,
  LockedClassesRoute: LockedClassesRoute,
  MappingRoute: MappingRoute,
  PriorityClassesRoute: PriorityClassesRoute,
  ReportsRoute: ReportsRoute,
  RoomsRoute: RoomsRoute,
  RoutineRoute: RoutineRoute,
  SectionsRoute: SectionsRoute,
  SemesterSettingsRoute: SemesterSettingsRoute,
  SettingsRoute: SettingsRoute,
  TeachersRoute: TeachersRoute,
  CtScheduleConfigRoute: CtScheduleConfigRoute,
  CtScheduleRoomsRoute: CtScheduleRoomsRoute,
  CtScheduleTableRoute: CtScheduleTableRoute,
  CtScheduleTeachersRoute: CtScheduleTeachersRoute,
  CtScheduleViewRoute: CtScheduleViewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
