/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TeachersRouteImport } from './routes/teachers'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SemesterSettingsRouteImport } from './routes/semester-settings'
import { Route as SectionsRouteImport } from './routes/sections'
import { Route as RoutineRouteImport } from './routes/routine'
import { Route as RoomsRouteImport } from './routes/rooms'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as CoursesRouteImport } from './routes/courses'
import { Route as AvailabilityRouteImport } from './routes/availability'
import { Route as IndexRouteImport } from './routes/index'

const TeachersRoute = TeachersRouteImport.update({
  id: '/teachers',
  path: '/teachers',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SemesterSettingsRoute = SemesterSettingsRouteImport.update({
  id: '/semester-settings',
  path: '/semester-settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SectionsRoute = SectionsRouteImport.update({
  id: '/sections',
  path: '/sections',
  getParentRoute: () => rootRouteImport,
} as any)
const RoutineRoute = RoutineRouteImport.update({
  id: '/routine',
  path: '/routine',
  getParentRoute: () => rootRouteImport,
} as any)
const RoomsRoute = RoomsRouteImport.update({
  id: '/rooms',
  path: '/rooms',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesRoute = CoursesRouteImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => rootRouteImport,
} as any)
const AvailabilityRoute = AvailabilityRouteImport.update({
  id: '/availability',
  path: '/availability',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/availability': typeof AvailabilityRoute
  '/courses': typeof CoursesRoute
  '/reports': typeof ReportsRoute
  '/rooms': typeof RoomsRoute
  '/routine': typeof RoutineRoute
  '/sections': typeof SectionsRoute
  '/semester-settings': typeof SemesterSettingsRoute
  '/settings': typeof SettingsRoute
  '/teachers': typeof TeachersRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/availability': typeof AvailabilityRoute
  '/courses': typeof CoursesRoute
  '/reports': typeof ReportsRoute
  '/rooms': typeof RoomsRoute
  '/routine': typeof RoutineRoute
  '/sections': typeof SectionsRoute
  '/semester-settings': typeof SemesterSettingsRoute
  '/settings': typeof SettingsRoute
  '/teachers': typeof TeachersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/availability': typeof AvailabilityRoute
  '/courses': typeof CoursesRoute
  '/reports': typeof ReportsRoute
  '/rooms': typeof RoomsRoute
  '/routine': typeof RoutineRoute
  '/sections': typeof SectionsRoute
  '/semester-settings': typeof SemesterSettingsRoute
  '/settings': typeof SettingsRoute
  '/teachers': typeof TeachersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/availability'
    | '/courses'
    | '/reports'
    | '/rooms'
    | '/routine'
    | '/sections'
    | '/semester-settings'
    | '/settings'
    | '/teachers'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/availability'
    | '/courses'
    | '/reports'
    | '/rooms'
    | '/routine'
    | '/sections'
    | '/semester-settings'
    | '/settings'
    | '/teachers'
  id:
    | '__root__'
    | '/'
    | '/availability'
    | '/courses'
    | '/reports'
    | '/rooms'
    | '/routine'
    | '/sections'
    | '/semester-settings'
    | '/settings'
    | '/teachers'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AvailabilityRoute: typeof AvailabilityRoute
  CoursesRoute: typeof CoursesRoute
  ReportsRoute: typeof ReportsRoute
  RoomsRoute: typeof RoomsRoute
  RoutineRoute: typeof RoutineRoute
  SectionsRoute: typeof SectionsRoute
  SemesterSettingsRoute: typeof SemesterSettingsRoute
  SettingsRoute: typeof SettingsRoute
  TeachersRoute: typeof TeachersRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/teachers': {
      id: '/teachers'
      path: '/teachers'
      fullPath: '/teachers'
      preLoaderRoute: typeof TeachersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/semester-settings': {
      id: '/semester-settings'
      path: '/semester-settings'
      fullPath: '/semester-settings'
      preLoaderRoute: typeof SemesterSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sections': {
      id: '/sections'
      path: '/sections'
      fullPath: '/sections'
      preLoaderRoute: typeof SectionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/routine': {
      id: '/routine'
      path: '/routine'
      fullPath: '/routine'
      preLoaderRoute: typeof RoutineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rooms': {
      id: '/rooms'
      path: '/rooms'
      fullPath: '/rooms'
      preLoaderRoute: typeof RoomsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses': {
      id: '/courses'
      path: '/courses'
      fullPath: '/courses'
      preLoaderRoute: typeof CoursesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/availability': {
      id: '/availability'
      path: '/availability'
      fullPath: '/availability'
      preLoaderRoute: typeof AvailabilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AvailabilityRoute: AvailabilityRoute,
  CoursesRoute: CoursesRoute,
  ReportsRoute: ReportsRoute,
  RoomsRoute: RoomsRoute,
  RoutineRoute: RoutineRoute,
  SectionsRoute: SectionsRoute,
  SemesterSettingsRoute: SemesterSettingsRoute,
  SettingsRoute: SettingsRoute,
  TeachersRoute: TeachersRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
